import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id "legacy-looming" version "${loom_version}"
    id 'java'
    id "org.jetbrains.kotlin.jvm" version "1.9.24"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}


kotlin {
    jvmToolchain(8)
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += "-Xjvm-default=all-compatibility"
    }
}


loom {
    runs {
        client {
            programArgs("--accessToken", "0", "--version", "1.8.9", "--userProperties", "{}", "--tweakClass", "me.miki.shindo.injection.mixin.ShindoTweaker")
            setMainClass("net.minecraft.launchwrapper.Launch")
        }
    }
}

legacyLooming {}


repositories {
    mavenCentral()
    maven { url 'https://raw.githubusercontent.com/BleachDev/cursed-mappings/main/' }
    maven { url 'https://repo.spongepowered.org/maven/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings(legacy.yarn(project.minecraft_version, project.yarn_build))

    implementation "net.minecraft:launchwrapper:1.12"
    implementation "org.ow2.asm:asm-all:5.0.3"
    implementation "org.spongepowered:mixin:0.7.11-SNAPSHOT"
    implementation "javax.annotation:javax.annotation-api:1.3.2"

    implementation "org.json:json:20240303"

    implementation files("libs/lwjgl-shindo.jar")
    implementation files("libs/lwjgl-shindo-natives.jar")

    implementation files("libs/ViaBackwards-4.7.0-1.20-pre1-SNAPSHOT.jar")
    implementation files("libs/ViaRewind-2.0.4-SNAPSHOT.jar")
    implementation files("libs/ViaVersion-4.7.0-1.20-pre2-SNAPSHOT.jar")
    implementation files("libs/snakeyaml-2.0.jar")

    implementation "com.fasterxml.jackson.core:jackson-databind:2.19.2"
    implementation "org.apache.httpcomponents.client5:httpclient5-cache:5.5"
    implementation "com.google.code.gson:gson:2.13.1"
    implementation "org.java-websocket:Java-WebSocket:1.6.0"
    implementation "net.lenni0451.commons:httpclient:1.9.0"
    implementation "net.lenni0451.commons:gson:1.9.0"
    implementation "io.arrow-kt:arrow-core:1.2.4"
}


tasks.named("runClient") {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

jar {
    manifest.attributes(
            "MixinConfigs": 'mixins.shindo.json',
            "TweakClass": 'me.miki.shindo.injection.mixin.ShindoTweaker',
            "TweakOrder": 0,
            "Manifest-Version": 1.0,
            'FMLAT': 'shindo_at.cfg'
    )
}
